module.exports = {
  "overrides": [
    {
      "files": ["*.ts", "*.tsx"],
      rules: {
        '@typescript-eslint/adjacent-overload-signatures': 2,
        '@typescript-eslint/explicit-function-return-type': 2,
        '@typescript-eslint/ban-ts-comment': 2,
        '@typescript-eslint/ban-types': 2,
        'no-array-constructor': 'off',
        '@typescript-eslint/no-array-constructor': 2,
        'no-empty-function': 'off',
        '@typescript-eslint/no-empty-function': 2,
        '@typescript-eslint/no-empty-interface': 2,
        '@typescript-eslint/no-explicit-any': 2,
        '@typescript-eslint/no-extra-non-null-assertion': 2,
        'no-extra-semi': 'off',
        '@typescript-eslint/no-extra-semi': 2,
        '@typescript-eslint/no-inferrable-types': 2,
        'no-loss-of-precision': 'off',
        '@typescript-eslint/no-loss-of-precision': 2,
        '@typescript-eslint/no-misused-new': 2,
        '@typescript-eslint/no-namespace': 2,
        '@typescript-eslint/no-non-null-asserted-optional-chain': 2,
        '@typescript-eslint/no-non-null-assertion': 'warn',
        '@typescript-eslint/no-this-alias': 2,
        '@typescript-eslint/no-unnecessary-type-constraint': 2,
        'no-unused-vars': 'off',
        '@typescript-eslint/no-unused-vars': 'warn',
        '@typescript-eslint/no-var-requires': 2,
        '@typescript-eslint/prefer-as-const': 2,
        '@typescript-eslint/prefer-namespace-keyword': 2,
        '@typescript-eslint/triple-slash-reference': 2,
        '@typescript-eslint/member-delimiter-style': [1, {
          multiline: {delimiter: "comma", requireLast: true},
          singleline: {delimiter: "comma", requireLast: false},
          multilineDetection: "brackets",
        }],
        "no-dupe-class-members": 0,
        "@typescript-eslint/no-dupe-class-members": 1,
        '@typescript-eslint/no-duplicate-enum-values': 2,
        "no-invalid-this": 0,
        "@typescript-eslint/no-invalid-this": 2,
        '@typescript-eslint/no-invalid-void-type': 2,
        "no-redeclare": 0,
        "@typescript-eslint/no-redeclare": 2,
        '@typescript-eslint/no-unnecessary-condition': 0,
        "no-shadow": 0,
        "@typescript-eslint/no-shadow": 2,
        "quotes": 0,
        "@typescript-eslint/quotes": [1, 'single'],
        '@typescript-eslint/strict-boolean-expressions': 2,
        '@typescript-eslint/switch-exhaustiveness-check': 2,
        '@typescript-eslint/unified-signatures': 1,
        "@typescript-eslint/consistent-type-imports": 2,
        '@typescript-eslint/consistent-type-exports': 2,

        '@typescript-eslint/type-annotation-spacing': 1
      }
    }
  ],
}
